"""Tests for ``aviary_immich.cli`` argument parsing and shell wiring.

``main()`` needs a live Immich server + GPU, so it is never invoked here. We exercise
``parse_args()`` (driven via ``sys.argv``) and the lazy-import discipline that keeps importing
the CLI from pulling in the GPU/ML stack.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

import aviary_immich.cli as cli


# --------------------------------------------------------------------------- helpers


def _parse(monkeypatch, *extra_args, env_file: Path):
    """Run ``parse_args`` with a controlled argv.

    Always pass ``--env-file`` pointing at a nonexistent path so ``load_env_file`` is a no-op
    and the test does not depend on a real ``.env``.
    """
    argv = ["generate-albums", "--env-file", str(env_file), *extra_args]
    monkeypatch.setattr(sys, "argv", argv)
    return cli.parse_args()


@pytest.fixture
def missing_env(tmp_path):
    """A path under tmp that does not exist, so ``load_env_file`` short-circuits."""
    return tmp_path / "does-not-exist.env"


# --------------------------------------------------------------------------- album description


def test_album_description_includes_updated_date():
    assert cli.album_description("2026-06-09") == "Auto-generated by Aviary. Last updated 2026-06-09."


# --------------------------------------------------------------------------- asset dedup


def test_dedupe_by_id_drops_duplicates_keeping_first():
    # Immich pagination can yield the same asset twice if the library mutates mid-scan; deduping
    # before the scan partition keeps each id from being enqueued (and its thumbnail raced) twice.
    assets = [
        {"id": "a", "originalFileName": "first.jpg"},
        {"id": "b", "originalFileName": "b.jpg"},
        {"id": "a", "originalFileName": "second.jpg"},
    ]
    deduped = cli.dedupe_by_id(assets)
    assert [a["id"] for a in deduped] == ["a", "b"]
    # First occurrence wins, not the later duplicate.
    assert deduped[0]["originalFileName"] == "first.jpg"


def test_dedupe_by_id_preserves_order_when_no_duplicates():
    assets = [{"id": "x"}, {"id": "y"}, {"id": "z"}]
    assert cli.dedupe_by_id(assets) == assets


def test_dedupe_by_id_coerces_ids_to_str_like_state_keys():
    # State and assets_by_id are keyed by str(asset["id"]); the dedup must match that coercion so
    # an int and its string form collapse to one entry.
    assets = [{"id": 5}, {"id": "5"}]
    assert cli.dedupe_by_id(assets) == [{"id": 5}]


# --------------------------------------------------------------------------- defaults


def test_threshold_default(monkeypatch, missing_env):
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.threshold == 0.30


def test_device_default(monkeypatch, missing_env):
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.device == "auto"


def test_page_size_default(monkeypatch, missing_env):
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.page_size == 250


def test_batch_size_default(monkeypatch, missing_env):
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.batch_size == 100


def test_model_default(monkeypatch, missing_env):
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.model == "yolo11x.pt"


def test_thumbnail_size_default(monkeypatch, missing_env):
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.thumbnail_size == "preview"


def test_chunk_size_default(monkeypatch, missing_env):
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.chunk_size == 1000


def test_inference_batch_size_default(monkeypatch, missing_env):
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.inference_batch_size == 64


def test_prefetch_default(monkeypatch, missing_env):
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.prefetch == 2


def test_cpu_workers_default(monkeypatch, missing_env):
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.cpu_workers == -1


def test_path_defaults_are_paths(monkeypatch, missing_env):
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.accounts_config == Path("models/immich/config/accounts.yaml")
    assert args.cache_dir == Path("models/immich/data/cache")
    assert args.state_dir == Path("models/immich/data/state")
    assert args.manifest_dir == Path("models/immich/data/manifests")


def test_limit_default_is_none(monkeypatch, missing_env):
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.limit is None


def test_boolean_flags_default_false(monkeypatch, missing_env):
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.force_rescan is False
    assert args.dry_run is False
    assert args.cpu_only is False
    assert args.gpu_only is False
    assert args.keep_cache is False


# --------------------------------------------------------------------------- video args


def test_video_defaults(monkeypatch, missing_env):
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.skip_videos is False
    assert args.video_every_seconds == 1.0
    assert args.video_max_frames == 30
    assert args.video_max_edge == 1280
    assert args.video_transcoded is True


def test_skip_videos_flag(monkeypatch, missing_env):
    args = _parse(monkeypatch, "--skip-videos", env_file=missing_env)
    assert args.skip_videos is True


def test_video_original_clears_transcoded(monkeypatch, missing_env):
    args = _parse(monkeypatch, "--video-original", env_file=missing_env)
    assert args.video_transcoded is False


def test_video_sampling_explicit_values(monkeypatch, missing_env):
    args = _parse(
        monkeypatch,
        "--video-every-seconds", "2.5",
        "--video-max-frames", "10",
        "--video-max-edge", "0",
        env_file=missing_env,
    )
    assert args.video_every_seconds == 2.5
    assert args.video_max_frames == 10
    assert args.video_max_edge == 0


# --------------------------------------------------------------------------- env overrides


def test_threshold_env_override(monkeypatch, missing_env):
    # The float default is read from the environment at parse time, so setting it before a fresh
    # parse must change the default.
    monkeypatch.setenv("IMMICH_BIRD_THRESHOLD", "0.5")
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.threshold == 0.5


def test_device_env_override(monkeypatch, missing_env):
    monkeypatch.setenv("IMMICH_BIRD_DEVICE", "cuda:1")
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.device == "cuda:1"


def test_model_env_override(monkeypatch, missing_env):
    monkeypatch.setenv("IMMICH_BIRD_MODEL", "yolo11n.pt")
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.model == "yolo11n.pt"


def test_thumbnail_size_env_override(monkeypatch, missing_env):
    monkeypatch.setenv("IMMICH_THUMBNAIL_SIZE", "fullsize")
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.thumbnail_size == "fullsize"


def test_workers_env_override(monkeypatch, missing_env):
    monkeypatch.setenv("IMMICH_BIRD_WORKERS", "7")
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.workers == 7


def test_explicit_flag_beats_env(monkeypatch, missing_env):
    # An explicit --threshold on the command line wins over the env-derived default.
    monkeypatch.setenv("IMMICH_BIRD_THRESHOLD", "0.5")
    args = _parse(monkeypatch, "--threshold", "0.9", env_file=missing_env)
    assert args.threshold == 0.9


# --------------------------------------------------------------------------- explicit values


def test_dry_run_sets_boolean(monkeypatch, missing_env):
    args = _parse(monkeypatch, "--dry-run", env_file=missing_env)
    assert args.dry_run is True


def test_force_rescan_sets_boolean(monkeypatch, missing_env):
    args = _parse(monkeypatch, "--force-rescan", env_file=missing_env)
    assert args.force_rescan is True


def test_cpu_only_sets_boolean(monkeypatch, missing_env):
    args = _parse(monkeypatch, "--cpu-only", env_file=missing_env)
    assert args.cpu_only is True
    assert args.gpu_only is False


def test_gpu_only_sets_boolean(monkeypatch, missing_env):
    args = _parse(monkeypatch, "--gpu-only", env_file=missing_env)
    assert args.gpu_only is True
    assert args.cpu_only is False


def test_limit_explicit_int(monkeypatch, missing_env):
    args = _parse(monkeypatch, "--limit", "42", env_file=missing_env)
    assert args.limit == 42


def test_page_and_batch_explicit(monkeypatch, missing_env):
    args = _parse(monkeypatch, "--page-size", "10", "--batch-size", "5", env_file=missing_env)
    assert args.page_size == 10
    assert args.batch_size == 5


def test_env_file_arg_is_path(monkeypatch, missing_env):
    args = _parse(monkeypatch, env_file=missing_env)
    assert args.env_file == missing_env


# --------------------------------------------------------------------------- mutual exclusion


def test_cpu_only_and_gpu_only_mutually_exclusive(monkeypatch, missing_env):
    with pytest.raises(SystemExit):
        _parse(monkeypatch, "--cpu-only", "--gpu-only", env_file=missing_env)


# --------------------------------------------------------------------------- .env loading


def test_env_file_missing_is_noop(monkeypatch, missing_env):
    # A nonexistent --env-file must not error: load_env_file short-circuits on a missing path.
    assert not missing_env.exists()
    args = _parse(monkeypatch, env_file=missing_env)
    # parse succeeded and the path round-trips
    assert args.env_file == missing_env


def test_env_file_is_loaded_into_environ(monkeypatch, tmp_path):
    # parse_args loads the .env first via load_env_file; values land in os.environ (setdefault),
    # so a threshold written into the env file becomes the parsed default.
    monkeypatch.delenv("IMMICH_BIRD_THRESHOLD", raising=False)
    env_file = tmp_path / "real.env"
    env_file.write_text("IMMICH_BIRD_THRESHOLD=0.75\n", encoding="utf-8")
    argv = ["generate-albums", "--env-file", str(env_file)]
    monkeypatch.setattr(sys, "argv", argv)
    args = cli.parse_args()
    assert args.threshold == 0.75


# --------------------------------------------------------------------------- shell wiring


def test_generate_albums_main_is_cli_main():
    import importlib

    generate_albums = importlib.import_module("generate_albums")
    assert generate_albums.main is cli.main


def test_importing_cli_does_not_pull_gpu_stack():
    # Robust regardless of test order / what else has been imported in this process: a clean
    # subprocess proves importing the CLI alone never imports torch or cv2.
    repo_root = Path(__file__).resolve().parents[3]
    src_dir = repo_root / "models" / "immich"
    env = dict(os.environ)
    # The source tree must be importable in the child interpreter; mirror pyproject's pythonpath.
    env["PYTHONPATH"] = str(src_dir) + os.pathsep + env.get("PYTHONPATH", "")
    result = subprocess.run(
        [
            sys.executable,
            "-c",
            "import sys; import aviary_immich.cli; "
            "assert 'torch' not in sys.modules and 'cv2' not in sys.modules",
        ],
        cwd=str(repo_root),
        env=env,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, f"stdout={result.stdout!r} stderr={result.stderr!r}"
