import type { Metadata, Viewport } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { SaveIndicator } from "@/components/SaveIndicator";
import { PointerModeClass } from "@/components/PointerModeClass";

export const metadata: Metadata = {
  applicationName: "Aviary Annotation",
  title: "Aviary Annotation",
  description: "Custom bird bounding-box annotation tool",
  // Installable home-screen app. The web manifest link is injected automatically
  // by app/manifest.ts; here we add the iOS-specific bits Safari needs to launch
  // full-screen and the icon set (generated by scripts/generate-icons.mjs).
  appleWebApp: {
    capable: true,
    title: "Aviary",
    // Opaque black bar — content sits below it, blending into the near-black UI
    // with no overlap (unlike "black-translucent", which would underlap chrome).
    statusBarStyle: "black",
  },
  formatDetection: { telephone: false },
  // Next 15 emits the standardized `mobile-web-app-capable`, but older iPadOS
  // only launches full-screen from the home screen when the legacy Apple tag is
  // present — add it explicitly so standalone mode works on every iOS version.
  other: { "apple-mobile-web-app-capable": "yes" },
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/icons/icon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
};

export const viewport: Viewport = {
  themeColor: "#0a0a0a",
  colorScheme: "dark",
  width: "device-width",
  initialScale: 1,
  // Extend under the iPad's rounded corners / home indicator so env(safe-area-*)
  // insets become available; bottom toolbars consume them (see globals.css).
  viewportFit: "cover",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body>
        <PointerModeClass />
        <SaveIndicator />
        {children}
      </body>
    </html>
  );
}
