"""Small Immich REST client for album generation and downloads."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import unquote

import requests


FILENAME_RE = re.compile(r'filename\*?=(?:UTF-8\'\')?"?([^";]+)"?', re.IGNORECASE)


class ImmichClient:
    def __init__(self, base_url: str, api_key: str, timeout_seconds: int = 60) -> None:
        self.base_url = base_url.rstrip("/")
        self.timeout_seconds = timeout_seconds
        self.session = requests.Session()
        self.session.headers.update(
            {
                "Accept": "application/json",
                "x-api-key": api_key,
            }
        )

    def get_my_user(self) -> dict[str, Any]:
        return self._request_json("GET", "/users/me")

    def list_albums(self) -> list[dict[str, Any]]:
        albums = self._request_json("GET", "/albums")
        if not isinstance(albums, list):
            raise ValueError("Immich /albums response was not a list")
        return albums

    def create_album(self, album_name: str) -> dict[str, Any]:
        return self._request_json(
            "POST",
            "/albums",
            json={
                "albumName": album_name,
                "description": "Auto-generated by Aviary bird detection.",
                "assetIds": [],
            },
        )

    def ensure_owned_album(self, album_name: str) -> dict[str, Any]:
        user = self.get_my_user()
        owner_id = str(user.get("id", ""))
        album = self.find_album(album_name, owner_id=owner_id, owned_only=True)
        if album:
            return album
        return self.create_album(album_name)

    def find_album(self, album_name: str, owner_id: str | None = None, owned_only: bool = False) -> dict[str, Any] | None:
        matches = [album for album in self.list_albums() if album.get("albumName") == album_name]
        if not matches:
            return None

        if owner_id:
            unknown_owner_matches: list[dict[str, Any]] = []
            for album in matches:
                album_owner_id = self._album_owner_id(album)
                if album_owner_id == owner_id:
                    return album
                if album_owner_id is None:
                    unknown_owner_matches.append(album)
            if owned_only:
                return unknown_owner_matches[0] if unknown_owner_matches else None

        return matches[0]

    def update_album(self, album_id: str, **fields: Any) -> Any:
        """Patch album metadata (e.g. ``description=...``) via ``PATCH /albums/{id}``."""
        return self._request_json("PATCH", f"/albums/{album_id}", json=fields)

    def add_assets_to_album(self, album_id: str, asset_ids: list[str]) -> Any:
        if not asset_ids:
            return []
        return self._request_json("PUT", f"/albums/{album_id}/assets", json={"ids": asset_ids})

    def iter_image_assets(self, page_size: int = 250, limit: int | None = None) -> Iterable[dict[str, Any]]:
        yield from self._iter_search_assets({"type": "IMAGE", "withExif": True}, page_size, limit)

    def iter_video_assets(self, page_size: int = 250, limit: int | None = None) -> Iterable[dict[str, Any]]:
        yield from self._iter_search_assets({"type": "VIDEO", "withExif": True}, page_size, limit)

    def iter_album_assets(
        self,
        album_id: str,
        page_size: int = 250,
        limit: int | None = None,
    ) -> Iterable[dict[str, Any]]:
        yield from self._iter_search_assets(
            {"type": "IMAGE", "withExif": True, "albumIds": [album_id]},
            page_size,
            limit,
        )

    def download_thumbnail(self, asset_id: str, path: Path, size: str = "preview") -> requests.structures.CaseInsensitiveDict:
        return self._download(f"/assets/{asset_id}/thumbnail", path, params={"size": size})

    def download_original(self, asset_id: str, path: Path) -> requests.structures.CaseInsensitiveDict:
        return self._download(f"/assets/{asset_id}/original", path)

    def download_video(self, asset_id: str, path: Path, transcoded: bool = True) -> requests.structures.CaseInsensitiveDict:
        """Download a video asset to ``path`` for frame sampling.

        ``transcoded=True`` fetches Immich's transcoded playback stream (smaller, cheaper to
        download and decode); ``transcoded=False`` fetches the untouched original. cv2 can't send
        the ``x-api-key`` header, so the bytes must land on disk before ``cv2.VideoCapture``.
        """
        if transcoded:
            return self._download(f"/assets/{asset_id}/video/playback", path)
        return self.download_original(asset_id, path)

    def _iter_search_assets(
        self,
        body: dict[str, Any],
        page_size: int,
        limit: int | None,
    ) -> Iterable[dict[str, Any]]:
        emitted = 0
        page = 1

        while True:
            request_body = dict(body)
            request_body.update({"page": page, "size": page_size})
            response = self._request_json("POST", "/search/metadata", json=request_body)
            assets_page = response.get("assets", {})
            items = assets_page.get("items", [])

            for item in items:
                yield item
                emitted += 1
                if limit is not None and emitted >= limit:
                    return

            next_page = assets_page.get("nextPage")
            if next_page:
                page = int(next_page)
                continue
            if len(items) < page_size:
                return
            page += 1

    def _download(
        self,
        path: str,
        destination: Path,
        params: dict[str, Any] | None = None,
    ) -> requests.structures.CaseInsensitiveDict:
        destination.parent.mkdir(parents=True, exist_ok=True)
        url = f"{self.base_url}{path}"
        with self.session.get(url, params=params, stream=True, timeout=self.timeout_seconds) as response:
            response.raise_for_status()
            with destination.open("wb") as handle:
                for chunk in response.iter_content(chunk_size=1024 * 1024):
                    if chunk:
                        handle.write(chunk)
            return response.headers

    def _request_json(self, method: str, path: str, **kwargs) -> Any:
        url = f"{self.base_url}{path}"
        response = self.session.request(method, url, timeout=self.timeout_seconds, **kwargs)
        response.raise_for_status()
        if not response.content:
            return None
        return response.json()

    @staticmethod
    def _album_owner_id(album: dict[str, Any]) -> str | None:
        if album.get("ownerId"):
            return str(album["ownerId"])
        owner = album.get("owner")
        if isinstance(owner, dict) and owner.get("id"):
            return str(owner["id"])
        return None


def filename_from_headers(headers: requests.structures.CaseInsensitiveDict) -> str | None:
    disposition = headers.get("content-disposition", "")
    match = FILENAME_RE.search(disposition)
    if not match:
        return None
    return unquote(match.group(1).strip())


def suffix_from_headers(headers: requests.structures.CaseInsensitiveDict, default: str = ".jpg") -> str:
    content_type = headers.get("content-type", "").split(";", 1)[0].strip().lower()
    return {
        "image/jpeg": ".jpg",
        "image/jpg": ".jpg",
        "image/png": ".png",
        "image/webp": ".webp",
        "image/heic": ".heic",
        "image/heif": ".heif",
    }.get(content_type, default)


def safe_filename(value: str, fallback: str) -> str:
    filename = (value or fallback).strip()
    filename = filename.replace("/", "_").replace("\\", "_")
    cleaned = "".join(char if char.isalnum() or char in {" ", ".", "-", "_"} else "_" for char in filename)
    return cleaned.strip(" .") or fallback
